### ISSUE TITLE
FLASH -> HTML5 Audio Player options?

### ISSUE THREAD

**Issue by syberknight** [matthewbuchanan/tumblr-kit#4]
hi,
i've not been able to find/figure-out a way to replace the "Flash" audio player with a more modern one (html5 w/flash fallback). 

do you know if it's even possible?
if so, any advice?

thanks!!!

**Comment by matthewbuchanan** [comment]
I haven’t looked at this in a while. You can get the audio file URL from a Tumblr tag but from memory it doesn’t work for all audio types (only externally hosted files I think). Pretty sure this is a copyright issue — HTML5 audio would make it too easy for people to steal tracks and Tumblr might then be forced to remove audio support to appease music labels.

**Comment by syberknight** [comment]
argh... ok - thanks for the quick reply!
