### ISSUE TITLE
JSRender Photoset Template IMG has a FIGURE enemy

### ISSUE THREAD

**Issue by syberknight** [matthewbuchanan/tumblr-kit#6]
hi, me again ;-)

i've noticed that anything i try to add around the IMG tag that's after the ELSE in the Photoset template gets obliterated when viewed in the browser page-source.

is that a JS-Render issue?

point of reference... `line 489` @ [http://sanctuaryinternational.com/test-tumblrkit](http://sanctuaryinternational.com/test-tumblrkit)

...shows `<img src="{{for photos}}{{:~getPhotoURL(#view, 800)}}{{/for}}" />`

if i add anything inside the `img` tag, like a `class` or `data` option, those go missing when the page is viewed.
likewise, if i try surrounding the `img` tag with an anchor/link `a href`, that goes missing too.

now, this only seems to be the case when Tumblr brings over an `img` that's _parented_ by a `figure` tag. so, not sure why some images get "_figured_" out & others don't, but when it does, it really messes with any customizations.

any thoughts on that?
THANKS!!!
-jason.

**Comment by matthewbuchanan** [comment]
Hmm. Tumblr does some rewriting of images that are included within content fields. You might be best to apply your styling by using a container on the image, so that the <figure> tag ends up inside the container, and the styles are applied from the container element. I think this is Tumblr at fault, not JSRender.

**Comment by syberknight** [comment]
hi Matthew, sorry for the delay.

so, i've been round'n'round with this & can't get it to work.

all the images that gets wrapped/rewritten by Tumblr with a `<figure...>` tag just obliterates any/everything i've tried. for example, just to see what could work i've tried things like...

```
<div style="border: 2px dashed red;">
    {{<img src="{{for photos}}{{:~getPhotoURL(#view, 800)}}{{/for}}" />}}
</div>
```

...as well as...

```
{{for photos}}
    <div style="border: 2px dashed red;">
        <img src="{{:~getPhotoURL(#view, 800)}}" />
    </div>
{{/for}}
```

...and even...

```
<p style="border: 2px dashed red;">testing above</p>

{{<img src="{{for photos}}{{:~getPhotoURL(#view, 800)}}{{/for}}" />}}
<!-- for both these two configurations separately -->
{{for photos}}<img src="{{:~getPhotoURL(#view, 800)}}" />{{/for}}

<p style="border: 2px dashed red;">testing below</p>
```

...and every time, it's ALL overwritten with the resulting `figure`>`img` markup.

i can understand Tumblr overwriting anything inside the `{{for photos}}` area, but how could it be also overwritting **EVERYTHING above & below** it that's within the `article` tag?

**Comment by syberknight** [comment]
hey, just checking in about this. any luck yet?
much appreciation!

**Comment by syberknight** [comment]
hey; i don't wanna be a pest, but... ;-)
would you have any time to look at this soon?
thanks!!

**Comment by syberknight** [comment]
hello, been a long time. this project got shelved for me soon after my last post. but it's now being resurrected. i'm just starting to pour over all my notes & code & had a link to this issue thread. wondering if anything ever came of it on your end(?). thanks.

**Comment by syberknight** [comment]
just an FYI to close this issue if you want...

i've had to just settle myself to generalizing styles for items that come thru with the 'figure' tag container. this seems to happen for any non-text content in the comment section of a post (picture, video, etc).

for the odd occasion when something is used but left blank, i added ":empty" to its css tag & gave it a display:none or some other styling i wanted.

and for the times an empty a href tag gets put around something, i added this css...
.some-container a[href=""] {
        color: #ccc;
        cursor: non-allowed;
        pointer-events: none;
}

the only other thing that seems to be broken (which may be on Tumblr's side) is the little "Read More" link option in text posts. that just simply doesn't come over in the embed. but no biggy.

hope that helps.

**Comment by matthewbuchanan** [comment]
Thanks for your work/input on this!
